fix(templates): absolute path on static call
When `collectstatic` is used with `ManifestStaticFilesStorage`, static files paths are always generated as relative, e.g. `css/django-pwa-app.css`. Calling `/css/django-pwa-app.css` results in
> ValueError: Missing staticfiles manifest entry for '/css/django-pwa-app.css'